---
title: "Impact of water deficit on growth, productivity, and water use efficiency in potato genotypes (*Solanum tuberosum* L.)"
author:
  - "Flavio Lozano-Isla ^1#^, Evelyn Farfan-Vignolo ^2#^, Raymundo Gutierrez ^3#^, Raul Blas ^3^, Khan Awais ^2#+^"
  - "^1^ Institute of Plant Breeding, Seed Science and Population Genetics, University of Hohenheim, Stuttgart, Germany."
  - "^2^ Dirección de Recursos Genéticos y Biotecnología, Instituto Nacional de Innovación Agraria (INIA), La Molina, Lima, Perú."
  - "^3^ Universidad Nacional Agraria La Molina (UNALM), Av. La Molina, 1558, Peru."
  - "^4^ Plant Pathology and Plant-Microbe Biology Section, Cornell University, Geneva, NY, 14456, USA."
  - "^#^ International Potato Center (CIP), Av. La Molina 1895, La Molina, 1558, Peru."
  - "^+^ Corresponding author."
date: "`r if (knitr:::is_html_output()) Sys.Date()`"
description: manuscript potato wue
github-repo: flavjack/20130515LM
site: bookdown::bookdown_site
documentclass: book
bookdown::gitbook:
output: 
  bookdown::word_document2: 
    reference_docx: files/style_rticles.docx
    number_sections: false
  bookdown::html_document2:
    toc: yes
    number_sections: yes
    toc_float: yes
always_allow_html: yes
link-citations: true
colorlinks: yes
bibliography: [files/book.bib, files/pkgs.bib]
csl: https://www.zotero.org/styles/apa
---

```{r setup, include=FALSE}
source("http://lozanoisla.com/setup.r")
library(readxl)
gsh <- paste0("https://docs.google.com/spreadsheets/d/"
              , "1dfgpmCKdPmxRHozrZp0iE_xMGsvKTIcztDpMWYSEGaY")
# browseURL(gsh)
gs <- as_sheets_id(gsh)
xl <- gs %>% drive_download("files/fieldbook.xlsx", overwrite = T) %>% pluck(2)
# fb <- xl %>% readxl::read_excel("fb") 
```

```{r igdocs, include=FALSE}
gdoc <- paste0("https://docs.google.com/document/d/"
               , "1osSykdzy6Kt20hK7yVL2fDLuA7kEHNsug6ejQFOpjUc")
# browseURL(gdoc)
googledrive::drive_download(file = gdoc
                            , path = "manuscript_project.txt"
                            , overwrite = T)
if(file.exists("manuscript_project.txt"))
  file.rename("manuscript_project.txt"
              , "manuscript_project.Rmd")
```

```{r child = "manuscript_project.Rmd", eval = T}
```

<!-- # REFERENCIAS -->

::: {#refs}
:::

```{r references}
if(!file.exists("files/pkgs.bib")) {write_bib(c(.packages()), "files/pkgs.bib")}
```
