# Materials and Methods

## Plant material and experimental design

Thirteen potato clones were selected from advanced breeding population collection at International Potato Center (CIP) and two commercial varieties were grown in an environmentally controlled greenhouse at CIP (La Molina Experimental Station) at 28/15°C day/night with 70±5% average relative humidity. 

The experiment was carried out in complete randomize block design where the first factor was the two irrigation treatments: well-watered (WW), treatment where the moisture was maintained at field capacit and water deficit (WD), treatment where the water requirements of each genotype measured at WW treatment until wilting point was reduced 10% inter-daily measurement and the second factor were compound by the fifteen potato genotypes, Table (\@ref(tab:genotypes)). The water decifit treatment were appliyed since 45 DAP and prior to the treatment initiation, the pots from both WW and WD treatments were watered to soaking and then allowed to drain overnight. Next day, the pots were sealed in a plastic bag secured with a twist tie to prevent water loss except by transpiration and all the pots were weighed and it was defined as the initial pot weight. 

Each experimental unit was composed for one tuber per pot (5 L) and It was sown containing two kg of dry commercial Sogemix SM2 (75% Peat Moss, perlite, vermiculite, and limestone). Fertilization was done twice with ammonium nitrate; triple superphosphate and potassium sulphate, one before planting (mix with the substrate) and the other applied at the surface at 40 DAP (days after planting). 


## Trait evaluation

### Transpiration and water use efficiency

Transpiration was calculated by weighing the pots every two days in the between 13:00 and 15:00 hours (GMT -05:00). The transpiration (TRS) of each plant was calculated by the procedure previously described by @Bhatnagar_Mathur_2007 and @Ray_1998. The inter-daily transpiration rates of WD plants were normalized against WW plant rates to reduce the influence of day-to-day variation ($TRS=\left(\frac{WD_{transpiration}}{WW_{transpiration\ average}}\right)$). The normalization was achieved by dividing transpiration of each individual plant in the WD regime by the mean transpiration of the WW plants. For compare the TRS between plants, a second normalization was done so that the normalized transpiration rate (NTR) of each plant was defined in 1.0 when the soil water content in each pot was at field capacity [@Sinclair_1986]. The available soil water or the fraction of transpirable soil water (FTSW), for each pot was calculated by dividing the pot weight minus the final pot weight by the transpirable soil water of that pot ($FTSW=\left(\frac{pot\ weight_{inter-daily}-pot\ weight_{final}}{pot\ weight_{initial}-pot\ weight_{final}}\right)$). 

The WUE in WD and WW plants was estimated from the total biomass and as weighted average for each of the plant components. WUE for the total biomass was calculated as the total biomass in dry weight produced during the treatment apply divided by the cumulative water transpired during the same period ([@Dalla_Costa_1997]. 

### Water components

The relative water conten (RWC) was determined by weighing the third leaflet (FW) from the third leaf from the apical part from the youngest fully expanded leaf of each plant. Each leaflet were placing in a 4x3 inch ziploc bag containing distilled water for 24 hours and after these time it was removed to taking turgid weight (TW) afterwards it was dried in an oven at 90 ºC for 24 hours and weighed (DW). The RWC was calculated according by [@Vasquez_Robinet_2008] by the formula $RWC\left(\%\right)=\left(\frac{leaflet_{FW}-leaflet_{DW}}{leaflet_{TW}-leaflet_{DW}}\right)\cdot100$.

Leaf osmotic potential (LOP) was determined using a dew point microvoltmeter (HR-33T Wescor Inc., Logan, UT, USA) with leaf discs of 5 mm diameter, taken from the third fully extended leaf. The leaf discs were put in 1 ml cryogenic tubes and frozen in liquid nitrogen for further analysis. The frozen leaves were incubated at 22°C for 30 min in a sealed C-52 chamber (Wescor Inc., Logan, UT, USA). The total osmotic adjustment (TOA) was defined as the difference in LOP between the WW and the WD plants [@Hessini_2009]. 

## Chlorophyll content (SPAD) 

The chlorophyll content of the plant was evaluated by taking SPAD measurements using a SPAD-502 chlorophyll meter (Konica Minolta Sensing, Inc., Osaka, Japan) from the third youngest fully expanded leaf from three points (upper, middle and lower leaflet of a leaf). Individual readings of leaflets were averaged to represent individual measurement of a leaf. The evaluations were done on light adapted leaves at 29, 59, 76, and 83 DAP. 

<!-- SPAD measurements of the leaf were used as an indicator of nitrogen status and leaf senescence.  -->

## Post-harvest traits and indices 

The harvest was at 90 DAP. The plants were separated in four components: leaves, stems, roots and tubers. The dry weight (g) components were determined by drying them at 80°C for 3 days in a forced air oven: leaf (LDW), stem (SDW), root (RWD), tuber (TDW). The leaf area (LFA) of the plants was measured in cm^2^ by taking photographs of all the leaves arranged on a wooden board and analyzing the pictures using SisCob v1.0 (EMBRAPA Instrumentação Agropecuária, 2003). 

The tolerance to decrease of water supply (TDWS) or the percentage of yield reduction was the index used to evaluated the drougth tolerance and it is used to characterize the response of each genotype to WD [@Deblonde_1999; @Lahlou_2003]. To calculate TDWS the TDW in WD treatment for every genotype was expressed relative to its TDW in the WW treatment. The harvest index (HI) was calculated as the ratio of TDW related to the total dry biomass (TDB) and specific leaf area (SLA) was calculated by dividing the LFA with LDW. 

## Statistical analysis

The experiment was carried out in a complete randomize block design with two factros; the irrigation treatments (WW and WD) and fifteen potato genotypes. Each treatment consisted of five replicates with one potato plant for experimental unit. Statistical analysis and graphs were performed in the statistical software R [@R-base; @R-GerminaR]. The analysis of variance (ANOVA) was performed to evaluate the differences between the factors and the comparison of the means with the Student-Newman-Keuls test (p<0.05) from agricoale package [@R-agricolae]. For the multivariate analysis correlation analysis was performed [@R-agricolae; @R-corrplot] and principal components analysis were made with FactoMineR package [@R-FactoMineR].

