# Result

Large differences existed among genotypes in total biomass dry weight (kgDW.m2) of well-watered (WW) plants at the end of the experiment (Figure 1a). Water deficit (WD) treatment had a significant effect (P < 0.001) with an average reduction of around 29% in comparison with the well-watered treatment (Figure 1a). CIP398190.89 was the only genotype with a 5% increase in biomass, and CIP398208.219 was the most affected by WD (~44% reduction in comparison with WW). In terms of productivity, WD decreased tuber yield (kgDW.m2) across genotypes by an average of 39% (P < 0.01), however, CIP398190.89 increased its productivity by 5%, while others like CIP398203.5 and CIP398203.244 presented up to 56% and 48% reduced tuber production (Figure 2a). CIP398190.89 had greater tuber dry weight (g) in WD compared to its yield in WW treatment, with a TDWS of 104.09%, indicating drought tolerance (Figure 1a). Most genotypes had similar performance under drought, such as UNICA (CIP392797.22) with 75.76% and CIP398208.33 with 71.9% TDWS. The genotypes CIP398203.244, CIP398208.219, and CIP398201.510 were among the most sensitive genotypes at 31.56, 46.75 and 48.88% respectively (Figure 1a). 

Differences among genotypes (p<0.001) and treatments (p<0.01) were found for harvest index (HI) (Figure 2b). Dry matter partitioning in CIP3977077.16 and CIP398190.89 under WD as shown by HI were not significantly different from that of the WW treatment. A strong negative correlation among root length and HI was found in both treatments (r= -0.73)
The specific leaf area (SLA) reduction was 48% under WD compared to WW (Figure 2c). CIP398190.89 together with CIP398203.5 were among the clones with lowest reduction (24 and 21% respectively), while CIP398208.219, CIP398098.119, and CIP398208.704 were among the clones with highest SLA reduction (53, 65, and 64% respectively).

There were significant (p<0.05) differences between genotypes for maximum rooting depth and stolon mass, but only stolon mass behaved differently under water deficit treatment (Figure 3). 

SPAD units taken over the course of plant development (29, 59, 76, and 83 DAP) showed that at 29 DAP all plants were at the same stress level as no treatment difference was found (Supplementary Table 1). By the end of the experiment, difference between treatment (T), genotypes (G), and G*T were found and the values were lower than at 29 DAP. WD values for all the genotypes were higher than the ones at WW conditions. The genotypes CIP398190.89 and CIP720088 had the lowest differences among treatments for SPAD at 83 DAP (2.06 and 0.30%, respectively), while CIP398203.244 and CIP398208.33 had the largest (14.48 and 17.54%, respectively) (Supplementary Table 1).

Leaf relative water content (RWC) significantly (p < 0.01) decreased in response to WD in all the genotypes (Supplementary Table 1). The values ranged between 64.96% and 50.09% for CIP720088 and CIP398201.510, respectively. Differences in osmotic potential (OP) among genotypes and treatments were also significant (P < .001) (Supplementary Table 1).

Water use efficiency (WUE) was generally higher in WD than WW plants (Figure 4a). Under WD treatment, CIP397077.16, CIP398208.620 and CIP398190.89 showed the highest efficiency (13.06, 12.03, and 11.59 g.L-1, respectively), while the lowest efficiencies (8.50 and 9.24 g.L-1) were presented by CIP398180.612 and CIP398203.5, respectively. CIP398208.620) (10.80 g.L-1 for WW and 12.03 g.L-1 for WD) and CIP398180.612 (8.36 g.L-1 for WW and 8.50 g.L-1) maintained similar WUE (higher or lower) in both treatments (Figure 3a). Tubers used a great portion of the water uptake (Figure 4b), at least for the tolerant genotypes (CIP398190.89, CIP397077.16, and UNICA), in which tubers either from WW or WD are alike (Sup.Fig.1). On the other hand, the sensitive genotype CIP398203.244 produced more leaves and stems rather than tubers. 

The values of total biomass (kgDW.m-2) and total transpiration (L) were strongly and positively correlated across (r= 0.92, P < .0001) all genotypes and per treatment (Fig.5a). WUE was also correlated with both total biomass and tuber yield (r = 0 .55, p < .05; and r = 0.78, p < 0.001 respectively) (Figure 5b and Supplemental Table 1). The efficiency of use of transpired water was 34.9% higher in CIP397077.16, compared to CIP398180.612. Genotypic variability was also noted in terms of TDWS and HI and three clear groups (tolerant, medium, sensitive) can be distinguished based on TDWS and HI. CIP397077.16, UNICA, CIP398208.620, and Achirana-INTA were ranked as tolerant while CIP398203.244 was rated as sensitive (Figure 5c). The leaf (r = 0.79), stem (r = 0.69), and tuber biomass (r = 0.56) were also positively correlated with transpiration. Almost all characteristics evaluated showed significant differences between treatments (Supplementary Table 2). Only SPAD29, before the start of the drought treatment, and root length did not show significant differences. 

